### ISSUE TITLE
Fail at npm install

### ISSUE THREAD

**Issue by Snow-HardWolf** [crowi/crowi#428]
## Overview

nmp install was failed
please help me

## environment

- AWS
- Centos7
- node v6.16.0
- mongodb v4.0.7

## Run

```
$ npm install
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN deprecated @fortawesome/fontawesome-free-webfonts@1.0.9: This package is deprecated. See https://git.io/fNCzJ for information about upgrading.
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam
npm WARN deprecated text-encoding@0.6.4: no longer maintained
強制終了       ....] - extract:yaml-loader: sill doParallel extract 1561
```

**Comment by lightnet328** [comment]
I do not know the version of Crowi that you are using.
Is it HEAD(`81e538d9ad3b51ea59a2dbc02f6bda118c5a9d01`) of the master branch?
Please use Node.js 8.x after `1.7.0`.
Ref. Https://github.com/crowi/crowi/pull/267

```
$ node -v
v6.16.0
$ npm -v
3.10.10
```

In the above environment, I could `npm i`.
But I do not recommend using those versions.

**Comment by Snow-HardWolf** [comment]
Thank you, @lightnet328 

I'm sorry I have to show version of Crowi
I used this 

```
$ git tag
v1.0.3
v1.0.4
v1.1.1
v1.1.2
v1.2.0
v1.3.0
v1.3.1
v1.4.0
v1.5.0
v1.5.1
v1.5.2
v1.5.3
v1.6.0
v1.6.1
v1.6.2
v1.6.3
v1.6.4
v1.6.5
v1.7.0
v1.7.1
v1.7.2
v1.7.3
v1.7.4
v1.7.5
v1.7.6

$ git branch
* (detached from v1.7.6)
  master

$ git show
commit 22db27ce4594ed3448de2e753fcd42b3f01f13f8
Merge: 27a7736 d4a6389
Author: otofune <otofune@gmail.com>
Date:   Fri Jan 11 16:14:54 2019 +0900

    Merge pull request #405 from crowi/wip-v1.7.6

    Prepare v1.7.6
```

and 

```
$ node -v
v6.16.0
$ npm -v
3.10.10
```

So , I change HEAD to (81e538d9ad3b51ea59a2dbc02f6bda118c5a9d01)

```
$ git checkout master
Previous HEAD position was 22db27c... Merge pull request #405 from crowi/wip-v1.7.6
Switched to branch 'master'

$ git show
commit 81e538d9ad3b51ea59a2dbc02f6bda118c5a9d01
Merge: 455ed22 37d89a1
Author: Sotaro KARASAWA <reg@sotaro-k.com>
Date:   Tue Mar 5 17:46:03 2019 +0900

    Merge pull request #417 from crowi/feature/slack-unfurl

    Unfurling links in slack messages

$ npm i

$ npm start

> crowi@1.7.6 start /home/crowi/crowi
> node app.js

/home/crowi/crowi/lib/crowi/index.js:127
    return { host, port, ...password }
                         ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/crowi/crowi/app.js:11:18)

npm ERR! Linux 3.10.0-957.1.3.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "start"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! crowi@1.7.6 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crowi@1.7.6 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the crowi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs crowi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls crowi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/crowi/crowi/npm-debug.log


```

The error has not changed at present.
Sorry, please lend me your help

**Comment by lightnet328** [comment]
@Snow-HardWolf 
Thank you for explaining it in detail.
I have not confirmed it, but I think the cause is probably due to the version of Node.js.
Please try using Node v8.11.2.

**Comment by Snow-HardWolf** [comment]
Thank you for your quick reply and polite explanation

The version of node was changed to 8.11.2 and it worked fine!

thank you very much!
Thanks to you


```

$ node -v
v8.11.2
[centos@ip-10-0-1-131 crowi]$ npm start

> crowi@1.7.6 start /home/centos/crowi
> node app.js

[development] Express server listening on port 3000

```
