### ISSUE TITLE
Cannot read property 'forEach' of undefined at lib/models/config.js:158:12

### ISSUE THREAD

**Issue by tknr** [crowi/crowi#91]
```
[hoge@crowi.huga.co.jp crowi]$ node -v && npm -v 
v4.4.5
2.15.5
[hoge@crowi.huga.co.jp crowi]$ cat /etc/redhat-release 
CentOS release 6.8 (Final)
[hoge@crowi.huga.co.jp crowi]$ PASSWORD_SEED=sample_seed MONGO_URI=mongodb://hoge:password@localhost:27017/crowi FILE_UPLOAD=local npm start

> crowi@1.4.0 start /home/hoge/crowi
> node app.js

/home/hoge/crowi/lib/models/config.js:158
        doc.forEach(function(el) {
           ^

TypeError: Cannot read property 'forEach' of undefined
    at /home/hoge/crowi/lib/models/config.js:158:12
    at /home/hoge/crowi/node_modules/mongoose/lib/query.js:2134:21
    at /home/hoge/crowi/node_modules/mongoose/node_modules/kareem/index.js:160:11
    at Immediate.cb (/home/hoge/crowi/node_modules/mongoose/lib/query.js:1033:14)
    at Immediate._onImmediate (/home/hoge/crowi/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

npm ERR! Linux 2.6.32-042stab108.5
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! crowi@1.4.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the crowi@1.4.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the crowi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs crowi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls crowi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hoge/crowi/npm-debug.log

```

**Comment by sotarok** [comment]
I cannot repro it so could you please give further information if you can.

I tried it with following envs

```
crowi => master (1.4.0 + dev)
node -v => 4.4.5
npm -v => 3.9.5
mongo --version => 3.0.7
```

By inserting debug code just before the line you reported,

```
...
156       .exec(function(err, doc) {
157         debug('loadAllConfig', err, doc);
158
159         doc.forEach(function(el) {
...
```

And I got the result below with an empty database.

```
crowi:models:config loadAllConfig +0ms null []
crowi:models:config Config loaded +2ms { crowi: {} }
```

As this result, doc is an empty array even if the database is empty, so it cannot be undefined.

**Comment by tknr** [comment]
changing mongodb settings made it fixed.
```
# Turn on/off security.  Off is currently the default
noauth = true
#auth = true
```
